CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS MPA_rating (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR,
    rating_id INTEGER REFERENCES MPA_rating (id),
    releaseDate DATE,
    duration INTEGER
);

CREATE TABLE IF NOT EXISTS film_genres (
    genre_id INTEGER REFERENCES genres (id),
    film_id BIGINT REFERENCES films (id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(200) NOT NULL,
    name VARCHAR(200),
    email VARCHAR(200),
    birthday DATE
);

CREATE TABLE IF NOT EXISTS user_friends (
    user1_id BIGINT REFERENCES users (id),
    user2_id BIGINT REFERENCES users (id),
    UNIQUE (user1_id, user2_id)
);

CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT REFERENCES films (id),
    user_id BIGINT REFERENCES users (id),
    UNIQUE (film_id, user_id)
);